### PR TITLE
add some unit tests for web project SWTOR.Web

### PR DESCRIPTION
**Pull request by dominiqueplante**
also fix small bug where in Anayzer you will get sequence is empty when FillEmptyDataPoints is called with  empty list

### CODE REVIEW

**Comment by trayburn** [comment]
Good stuff, unit tests for the Web project is where I was headed next. Well that plus cleaning up a bunch of that ugly code.  **Make sure you pull latest to your fork from master, I made major changes last night to the website to make log sharing possible**.

As always, thanks for the commit.

**Comment by dominiqueplante** [comment]
thanks for the heads up and accepting the pull requests :)  I stumbled upon your blog with the post on that gadget you got from MS for charging iPhones (met someone recently who also has one), and I stayed for the log parsing :)

I don't have the game, but I thought what you are doing looked interesting (in terms of API, data visualization, etc.).

I was going to look at getting some pie charts going.

I haven't played very  much with SignalR yet, but for this, it seemed like it would be cool for logs to be pumped in realtime and UI getting updated... What do you think?

**Comment by dominiqueplante** [comment]
Umm, can you give a quick rundown of what you are trying to do - I'm pretty sure I think I know - you are going to start persisting the logs in RavenDB - can you elaborate, etc?

**Comment by trayburn** [comment]
So the change that's live now is to start persisting not the logs, but
rather the Analysis artifact (CombatLog type).  I hash the incoming file,
and use it as a key to store the data.
I wanted to let people be able to share a URL with their friends, so they
can show off what they did in a combat.

Tim Rayburn
Principal Consultant, Improving Enterprises - Connected Systems MVP - Cell
817 760 0002 - Blog http://TimRayburn.net - Tim@TimRayburn.net

On Sun, Apr 1, 2012 at 11:33 AM, Dominique Plante <
reply@reply.github.com

**Comment by trayburn** [comment]
That code is actually live at SWTOR.AppHb.com right now if you want to see it in action.

Every push to Master is deployed there, immediately.  I love AppHarbor.

**Comment by dominiqueplante** [comment]
Um yes, I did say "logs", and I agree it does actually make more sense to store the analysis results  :)

how do you see this new code in action?

**Comment by trayburn** [comment]
Easiest way, get latest from master, and run in debug mode.  It will host a
version of RavenDB in the web process and shouldn't require anything else
special to setup.  To run in release mode you need to execute the
raven-start.bat first, which will launch the db server, and then run in
release mode.

Tim Rayburn
Principal Consultant, Improving Enterprises - Connected Systems MVP - Cell
817 760 0002 - Blog http://TimRayburn.net - Tim@TimRayburn.net

On Sun, Apr 1, 2012 at 3:00 PM, Dominique Plante <
reply@reply.github.com

**Pull request merged**
